language: cpp

addons:
  apt:
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
    - gcc-5
    - g++-5

compiler:
    - gcc

before_script:
    - mkdir build
    - cd build
    - export CC=gcc-5
    - export CXX=g++-5
    - cmake -DSPARQL=1 -DJAVA=1 ..

script:
    - make

dist: xenial
sudo: false
